language: ruby
cache: bundler
rvm:
- 2.3.0
deploy:
  skip_cleanup: true
  provider: rubygems
  gem: etheruby
  on:
    tags: true
    repo: MechanicalSloth/etheruby
  api_key:
    secure: gYVc7jUvD8K5j5qZ1gYX6brz/MalT1pTK2TlD4hf45VMZAyNM7w3ou2mOJd0NiJc87npwdUpgOV4KGq8IESZ13WDArntyGLAgCcRpGIYXLjXgh4WPMAJlQeQgIy+tpLE3V/d7TF0D+Rz67v3L27wLACoAV4/qRPFJIJWzYAwetSVH40en7cQl+Dr23mqA0CRGnVe3l8FxTZySKHsOumNN0Zyxj8xSteWIiNr/+sRPupSM4tbfcKg1p935b9lkHsYjWNcxhui5htAzGmBijWxr3DazWKynNWnB0iFStAXh4qCeXEmA0aVxpe++VH/5GBXm1hHhXP7rGNyCaOYAW9pEyCfIlFj2GCC5B0c595lt+MqiFWJ/bwD9puVnb+29bJDN91ilT/G03sSdB2RcvoQJa4WYDmwvWZuJBJn/NnxFpRHGvS7zKYcVqg7VUfK9htbNE+WbJjzPqGA7IgiTrGTJaq3lAGR1pzMUKtLfgwELxzUoyGnMTM4bl5VOXBDBLtv+QwVs3LBQ38Nmbj/M2QSPewdtjd+SRKwizBzIZ4sagQ/96GFZmqB1OWFZKC6x62CtJ3f0G1+EwZeZUohdWAtwvkDeccKtD19q/F4XA6ruWyYDax/Zbcp67D+lC1Dqm5KIhJZwpnIuxQzTq+7zQWZCBwmXZksT1SN4jO6mXWAYvI=
